### ISSUE TITLE
What is the ERB bands you used in your training and testing?

### ISSUE THREAD

**Issue by Helmholz** [afrancl/BinauralLocalizationCNN#2]
Thanks for the beautiful work! We are trying to play with your training code, but just found that the input cochelegram's dimension was 39, not the 36 you mentioned in your paper. Can you provide more information regarding the banding information actually used in your training and testing data? Like, what are the high and low limit of your erb band, and how is the filterbank generated? Can we invert your training data back to wav files, so that we can listen how the binaural inputs are like?

**Comment by afrancl** [comment]
Hi @Helmholz, I'm glad to hear you like the work. Sorry I missed your initial comment until now. You are right that it should say 39 instead of 36 cochlear channels in the paper. We are in the process of correcting this typo.

The cochleagrams are all generated using this lab codebase: https://github.com/mcdermottLab/pycochleagram. The high and low limits we used are 30 Hz to 20 kHz, yielding 39 bands. You can also use the cochleagram codebase to invert the subbands returned from that code. I hope this helps!

**Comment by Helmholz** [comment]
> Hi @Helmholz, I'm glad to hear you like the work. Sorry I missed your initial comment until now. You are right that it should say 39 instead of 36 cochlear channels in the paper. We are in the process of correcting this typo.
> 
> The cochleagrams are all generated using this lab codebase: https://github.com/mcdermottLab/pycochleagram. The high and low limits we used are 30 Hz to 20 kHz, yielding 39 bands. You can also use the cochleagram codebase to invert the subbands returned from that code. I hope this helps!

Yes, it helps! Thank you very much!
